export 'splash/splashscreen.dart';
export 'home/homescreen.dart';
export 'bottom_nav/bottom_nav.dart';
export 'onboarding/onboarding.dart';
export 'auth/login/login.dart';
export 'auth/sign_up/sign_up.dart';
export 'message/message_screen.dart';
export 'cart/cartscreen.dart';
export 'account/account_screen.dart';